### ISSUE TITLE
requirements.txt should not pin popular libraries

### ISSUE THREAD

**Issue by rwarren** [cloudsigma/pycloudsigma#10]
The `cloudsigma` package currently pins requirements with `==`.  This is a conflict in many cases for popular packages like `nose`, `requests`, and `six`, at least.

Since `cloudsigma` is a support library, to avoid conflicts with other imports it should set minimum version requirements with `>=` rather than pinning directly with `==`.

**Comment by jjlopez** [comment]
Hi @rwarren.

I'll review it and make the necessary changes.
Thanks for your suggestion.

Regards.

**Comment by rwarren** [comment]
Hi @jjlopez .  This is still a problem.  Any chance of an update?

**Comment by miguel-cs** [comment]
Fixed in v0.5
